### ISSUE TITLE
Tilled Soil too good

### ISSUE THREAD

**Issue by ghost** [Tammabanana/Initial-Conditions-Subsistence#3]
1.2 fertility for only 0.85s work per tile and no materials, wut. That's a massive balance changer.

**Comment by Tammabanana** [comment]
Craptastic. It's supposed to take longer to dig, but I haven't fully figured out the WorkToBuild A16 changes yet. Everything seems to be going faster than I meant it to. I think it's happening on the Kitchen Counters too. >.<

**Comment by Tammabanana** [comment]
Tilled soil removed, on account of how you can accidentally make Rich Soil less fertile by tilling over it, I couldn't figure out how to fix that, and I like Rainbeau's Fertile Fields better.
